server.port=8080
stats.service.connect-timeout=10s
stats.service.read-timeout=20s

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always
spring.sql.init.schema=classpath:schema.sql

#---
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:6542/ewm-main
spring.datasource.username=root
spring.datasource.password=root
#---
spring.config.activate.on-profile=test
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:ewm-main
spring.datasource.username=root
spring.datasource.password=root