CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(250) NOT NULL,
    email VARCHAR(254) NOT NULL UNIQUE
);
CREATE INDEX IF NOT EXISTS idx_user_name ON users(name);
CREATE INDEX IF NOT EXISTS idx_user_email ON users(email);

CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);
CREATE INDEX IF NOT EXISTS idx_category_name ON categories(name);

CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation VARCHAR(2000) NOT NULL,
    category_id BIGINT NOT NULL REFERENCES categories(id) ON DELETE RESTRICT,
    confirmed_requests BIGINT DEFAULT 0,
    created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    description VARCHAR(7000) NOT NULL,
    event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    initiator_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    location_lat FLOAT NOT NULL,
    location_lon FLOAT NOT NULL,
    paid BOOLEAN NOT NULL DEFAULT FALSE,
    participant_limit INT NOT NULL DEFAULT 0,
    published_on TIMESTAMP WITHOUT TIME ZONE,
    request_moderation BOOLEAN NOT NULL DEFAULT TRUE,
    state VARCHAR(20) NOT NULL,
    title VARCHAR(120) NOT NULL,
    views BIGINT DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_event_state ON events(state);
CREATE INDEX IF NOT EXISTS idx_event_category_id ON events(category_id);
CREATE INDEX IF NOT EXISTS idx_event_initiator_id ON events(initiator_id);
CREATE INDEX IF NOT EXISTS idx_event_event_date ON events(event_date);

CREATE TABLE IF NOT EXISTS compilations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned BOOLEAN NOT NULL DEFAULT FALSE,
    title VARCHAR(50) NOT NULL UNIQUE
);
CREATE INDEX IF NOT EXISTS idx_compilation_pinned ON compilations(pinned);

CREATE TABLE IF NOT EXISTS compilations_events (
    compilation_id BIGINT REFERENCES compilations(id) ON DELETE CASCADE,
    event_id BIGINT REFERENCES events(id) ON DELETE CASCADE,
    PRIMARY KEY (compilation_id, event_id)
);

CREATE TABLE IF NOT EXISTS participation_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    requester_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    status VARCHAR(20) NOT NULL,
    UNIQUE (event_id, requester_id)
);
CREATE INDEX IF NOT EXISTS idx_request_event_id ON participation_requests(event_id);
CREATE INDEX IF NOT EXISTS idx_request_requester_id ON participation_requests(requester_id);
CREATE INDEX IF NOT EXISTS idx_request_status ON participation_requests(status);

CREATE TABLE IF NOT EXISTS event_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    commenter_id BIGINT NOT NULL REFERENCES users(id),
    text VARCHAR(2000) NOT NULL,
    created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_on TIMESTAMP WITHOUT TIME ZONE,
    posted_on TIMESTAMP WITHOUT TIME ZONE,
    status VARCHAR(20) NOT NULL,
    reason_delete VARCHAR(200),
    status_editor_id BIGINT REFERENCES users(id),
    status_changed_by_admin BOOLEAN NOT NULL DEFAULT FALSE,
    UNIQUE (event_id, commenter_id)
);
CREATE INDEX IF NOT EXISTS idx_comment_event_id ON event_comments(event_id);
CREATE INDEX IF NOT EXISTS idx_comment_commenter_id ON event_comments(commenter_id);
CREATE INDEX IF NOT EXISTS idx_comment_status ON event_comments(status);